### ISSUE TITLE
String misinterpretation in python 2.x

### ISSUE THREAD

**Issue by dannyvoid** [captainmeta4/AutoMod-Rule-Maker#2]
Problem arises while using Python 2.7.12 on Windows 7.

If you add a single domain the generated code comes out to this
`domain: [u'imgur.com']`

If you have multiple domains, but only seperate them with a comma you get this:
`domain: [u'imgur.com, reddit.com, gfycat.com']`

And, if you seperate each domain with a new line you get this:
`domain: [u'imgur.com', u'reddit.com', u'gfycat.com']`

Works without issue on Python 3.5.2 on Windows 7.
`domain: ['imgur.com', 'reddit.com', 'gfycat.com']`

I can't test on any other platform.

**Comment by captainmeta4** [comment]
This was developed in python 3.5 and 3.6; I didn't develop for backwards compatibility with python 2.x.

Will look into a method of enforcing python 3.x runtime.

**Comment by captainmeta4** [comment]
Mitigated in v1.2; it now checks what version of python it's running on.

At some point in the future I may add python 2.x compatibility.
