### ISSUE TITLE
importerror: No module named tkinter

### ISSUE THREAD

**Issue by hernikplays** [captainmeta4/AutoMod-Rule-Maker#9]
admins-MacBook-Pro:~ ------$ cd '/Users/-------/Downloads/AutoMod-Rule-Maker-master/' && '/usr/bin/pythonw'  '/Users/------/Downloads/AutoMod-Rule-Maker-master/AutoMod_Rule_Maker.pyw'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/-------/Downloads/AutoMod-Rule-Maker-master/AutoMod_Rule_Maker.pyw", line 1, in <module>
    from tkinter import *
ImportError: No module named tkinter

Using mac & python 3.6.2

**Comment by PokestarFan** [comment]
Tkinter is not on your system. Reinstall python after following these steps at https://www.python.org/download/mac/tcltk/
